# Generated by Django 2.2.4 on 2019-11-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20191010_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
